import type { Faction, DiplomaticRelation } from "@/types/game";

export const INITIAL_FACTIONS: Faction[] = [
  {
    id: "liu_bei",
    rulerName: "유비",
    isPlayer: true,
    gold: 10000,
    food: 20000,
    totalTroops: 80000,
    popularity: 65,
    cities: [
      { cityName: "신야", population: 50000, defense: 40, commerce: 55, agriculture: 60, garrison: 50000, governor: "제갈량", terrain: "평원", adjacentCities: ["완", "허창"] },
      { cityName: "하비", population: 35000, defense: 30, commerce: 45, agriculture: 70, garrison: 30000, governor: "미축", terrain: "평원", adjacentCities: ["소패", "서주"] },
    ],
    generals: [
      { generalName: "제갈량", warfare: 35, intelligence: 100, leadership: 92, politics: 95, charm: 92, loyalty: 100, currentTask: "참모", location: "신야" },
      { generalName: "관우", warfare: 97, intelligence: 75, leadership: 90, politics: 62, charm: 80, loyalty: 100, currentTask: "순찰", location: "신야" },
      { generalName: "장비", warfare: 98, intelligence: 30, leadership: 55, politics: 20, charm: 45, loyalty: 100, currentTask: "훈련", location: "신야" },
      { generalName: "조운", warfare: 92, intelligence: 76, leadership: 88, politics: 70, charm: 82, loyalty: 95, currentTask: "대기", location: "하비" },
      { generalName: "미축", warfare: 25, intelligence: 35, leadership: 45, politics: 88, charm: 90, loyalty: 88, currentTask: "세금징수", location: "하비" },
    ],
    recentEvents: [],
    pendingTasks: [],
    personality: { aggression: 30, diplomacy: 70, development: 80, riskTolerance: 40 },
    color: "#4a8c5c",
    icon: "🟢",
  },
  {
    id: "cao_cao",
    rulerName: "조조",
    isPlayer: false,
    gold: 80000,
    food: 120000,
    totalTroops: 1500000,
    popularity: 55,
    cities: [
      { cityName: "허창", population: 120000, defense: 75, commerce: 85, agriculture: 80, garrison: 300000, governor: "순욱", terrain: "평원", adjacentCities: ["신야", "완", "낙양", "진류"] },
      { cityName: "업", population: 100000, defense: 70, commerce: 75, agriculture: 75, garrison: 250000, governor: "하후돈", terrain: "평원", adjacentCities: ["낙양", "남피", "진류"] },
      { cityName: "낙양", population: 90000, defense: 80, commerce: 80, agriculture: 65, garrison: 200000, governor: "조인", terrain: "요새", adjacentCities: ["허창", "업", "장안"] },
      { cityName: "진류", population: 60000, defense: 55, commerce: 65, agriculture: 70, garrison: 150000, governor: "장료", terrain: "평원", adjacentCities: ["허창", "업", "소패"] },
      { cityName: "장안", population: 80000, defense: 70, commerce: 70, agriculture: 60, garrison: 150000, governor: "가후", terrain: "요새", adjacentCities: ["낙양", "한중"] },
    ],
    generals: [
      { generalName: "하후돈", warfare: 85, intelligence: 52, leadership: 80, politics: 45, charm: 55, loyalty: 100, currentTask: "순찰", location: "업" },
      { generalName: "장료", warfare: 92, intelligence: 72, leadership: 88, politics: 50, charm: 65, loyalty: 90, currentTask: "훈련", location: "진류" },
      { generalName: "순욱", warfare: 15, intelligence: 96, leadership: 70, politics: 98, charm: 88, loyalty: 95, currentTask: "내정", location: "허창" },
      { generalName: "가후", warfare: 30, intelligence: 97, leadership: 65, politics: 90, charm: 40, loyalty: 80, currentTask: "참모", location: "장안" },
      { generalName: "조인", warfare: 78, intelligence: 60, leadership: 82, politics: 55, charm: 50, loyalty: 95, currentTask: "방어", location: "낙양" },
      { generalName: "서황", warfare: 88, intelligence: 55, leadership: 78, politics: 40, charm: 52, loyalty: 92, currentTask: "훈련", location: "허창" },
    ],
    recentEvents: [],
    pendingTasks: [],
    personality: { aggression: 80, diplomacy: 50, development: 60, riskTolerance: 70 },
    color: "#4466aa",
    icon: "🔵",
  },
  {
    id: "sun_quan",
    rulerName: "손권",
    isPlayer: false,
    gold: 50000,
    food: 70000,
    totalTroops: 800000,
    popularity: 70,
    cities: [
      { cityName: "건업", population: 100000, defense: 65, commerce: 80, agriculture: 75, garrison: 250000, governor: "장소", terrain: "강", adjacentCities: ["시상", "여강"] },
      { cityName: "시상", population: 60000, defense: 55, commerce: 60, agriculture: 65, garrison: 150000, governor: "주유", terrain: "강", adjacentCities: ["건업", "강릉", "장사"] },
      { cityName: "여강", population: 45000, defense: 50, commerce: 55, agriculture: 60, garrison: 100000, governor: "여몽", terrain: "강", adjacentCities: ["건업", "소패"] },
    ],
    generals: [
      { generalName: "주유", warfare: 80, intelligence: 96, leadership: 90, politics: 80, charm: 88, loyalty: 100, currentTask: "참모", location: "시상" },
      { generalName: "여몽", warfare: 82, intelligence: 78, leadership: 76, politics: 55, charm: 60, loyalty: 92, currentTask: "순찰", location: "여강" },
      { generalName: "노숙", warfare: 30, intelligence: 90, leadership: 72, politics: 92, charm: 85, loyalty: 95, currentTask: "외교", location: "건업" },
      { generalName: "감녕", warfare: 90, intelligence: 40, leadership: 70, politics: 25, charm: 50, loyalty: 85, currentTask: "훈련", location: "시상" },
      { generalName: "장소", warfare: 20, intelligence: 82, leadership: 60, politics: 95, charm: 80, loyalty: 90, currentTask: "내정", location: "건업" },
    ],
    recentEvents: [],
    pendingTasks: [],
    personality: { aggression: 40, diplomacy: 75, development: 75, riskTolerance: 35 },
    color: "#d4443e",
    icon: "🔴",
  },
  {
    id: "yuan_shao",
    rulerName: "원소",
    isPlayer: false,
    gold: 60000,
    food: 90000,
    totalTroops: 1100000,
    popularity: 50,
    cities: [
      { cityName: "남피", population: 80000, defense: 60, commerce: 65, agriculture: 70, garrison: 300000, governor: "심배", terrain: "평원", adjacentCities: ["업", "기주"] },
      { cityName: "기주", population: 90000, defense: 65, commerce: 70, agriculture: 75, garrison: 250000, governor: "안량", terrain: "평원", adjacentCities: ["남피", "유주"] },
      { cityName: "유주", population: 55000, defense: 50, commerce: 50, agriculture: 55, garrison: 150000, governor: "문추", terrain: "산지", adjacentCities: ["기주"] },
    ],
    generals: [
      { generalName: "안량", warfare: 95, intelligence: 35, leadership: 60, politics: 20, charm: 30, loyalty: 88, currentTask: "훈련", location: "기주" },
      { generalName: "문추", warfare: 93, intelligence: 30, leadership: 55, politics: 15, charm: 28, loyalty: 85, currentTask: "순찰", location: "유주" },
      { generalName: "장합", warfare: 86, intelligence: 70, leadership: 82, politics: 50, charm: 55, loyalty: 70, currentTask: "대기", location: "남피" },
      { generalName: "심배", warfare: 40, intelligence: 72, leadership: 60, politics: 80, charm: 45, loyalty: 92, currentTask: "내정", location: "남피" },
      { generalName: "곽도", warfare: 20, intelligence: 75, leadership: 50, politics: 70, charm: 35, loyalty: 78, currentTask: "참모", location: "기주" },
    ],
    recentEvents: [],
    pendingTasks: [],
    personality: { aggression: 60, diplomacy: 35, development: 50, riskTolerance: 55 },
    color: "#c9a84c",
    icon: "🟡",
  },
];

export const INITIAL_RELATIONS: DiplomaticRelation[] = [
  { factionA: "liu_bei", factionB: "cao_cao", type: "적대", score: -40, treaties: [] },
  { factionA: "liu_bei", factionB: "sun_quan", type: "우호", score: 30, treaties: [] },
  { factionA: "liu_bei", factionB: "yuan_shao", type: "중립", score: 0, treaties: [] },
  { factionA: "cao_cao", factionB: "sun_quan", type: "적대", score: -30, treaties: [] },
  { factionA: "cao_cao", factionB: "yuan_shao", type: "전쟁", score: -70, treaties: [] },
  { factionA: "sun_quan", factionB: "yuan_shao", type: "중립", score: 10, treaties: [] },
];

export const FACTION_NAMES: Record<string, string> = {
  liu_bei: "유비",
  cao_cao: "조조",
  sun_quan: "손권",
  yuan_shao: "원소",
};
